README.md

Edits:
- Converted all YAML to proper JSON
- Snippets formatting
- Proper .MD code encapsulation.

Code formatting fix

---

doc/examples/079-login-auth-headers/config.json
doc/examples/080-login-auth-query/config.json
doc/examples/081-login-auth-headers-query-override/config.json
doc/examples/082-login-auth-expires/config.json
doc/examples/083-login-auth-expires-date/config.json
doc/examples/084-login-auth-expires-seconds/config.json
doc/examples/117-function-login-params-response/_sample_out/mock-server.users
doc/examples/117-function-login-params-response/_sample_out/mock-server.users.manifest
doc/examples/117-function-login-params-response/auth.request
doc/examples/117-function-login-params-response/auth.requestHeaders
doc/examples/117-function-login-params-response/auth.response
doc/examples/117-function-login-params-response/config.json
doc/examples/117-function-login-params-response/users.request
doc/examples/117-function-login-params-response/users.response
doc/examples/118-function-login-headers-response/_sample_out/mock-server.users
doc/examples/118-function-login-headers-response/_sample_out/mock-server.users.manifest
doc/examples/118-function-login-headers-response/auth.request
doc/examples/118-function-login-headers-response/auth.requestHeaders
doc/examples/118-function-login-headers-response/auth.response
doc/examples/118-function-login-headers-response/config.json
doc/examples/118-function-login-headers-response/users.request
doc/examples/118-function-login-headers-response/users.requestHeaders
doc/examples/118-function-login-headers-response/users.response
src/Authentication/Login.php
src/Authentication/OAuth20.php
tests/Authentication/LoginTest.php

Allow functions in authentication.apiRequest.headers

---

src/MissingTableHelper.php
tests/MissingTableHelperTest.php

fix: support shorthand mapping - undocumented, but working and used
https://github.com/keboola/php-csvmap/blob/master/src/Keboola/CsvMap/Mapper.php#L50

fix support shorthand mapping

---

src/MissingTableHelper.php
tests/MissingTableHelperTest.php

fix: output bucket is not required for components based on generic, which have default bucket on

fix output bucket

---

src/MissingTableHelper.php
tests/MissingTableHelperTest.php

znova znova znova znova znova znova 
https://www.karaoketexty.cz/texty-pisni/kopytovci/makky-messer-517734

fix: root table mapping

---

src/MissingTableHelper.php
tests/MissingTableHelperTest.php

it's actually named `incrementalOutput` and not `incremental` https://developers.keboola.com/extend/generic-extractor/incremental/

fix: naming of incremental output flag

---

src/MissingTableHelper.php
tests/MissingTableHelperTest.php

- do not create parentKey in table, if disabled in mapping

fix (MissingTableHelper): ParentKey disable

---

composer.json
composer.lock

Solving: https://keboola.atlassian.net/browse/COM-371
Changes:
- Update `keboola/juicer` to add ability to change path `delimiter` in `ResponseUrlScroller`, read more: https://github.com/keboola/juicer/pull/28

Update keboola/juicer 4.7 -> 4.8

---

composer.json
composer.lock
src/Configuration/UserFunction.php
tests/Config/UserFunctionTest.php

Jira: https://keboola.atlassian.net/browse/COM-564

Check type of $functions in the UserFunction::build

---

composer.json
composer.lock

Jira: https://keboola.atlassian.net/browse/COM-580
Juicer changes: https://github.com/keboola/juicer/pull/30

Update keboola/juicer -> 4.9.1

---

composer.json
composer.lock

Jira: https://keboola.atlassian.net/browse/COM-622
Juicer changes: https://github.com/keboola/juicer/pull/33

Fix types, explicitly define type

---

src/Authentication/Login.php
src/Authentication/OAuth10.php
src/Authentication/OAuth20.php
src/Authentication/OAuth20Login.php
src/Configuration/Api.php
src/Context/OAuth20Context.php
src/Context/OAuth20LoginContext.php
src/Context/RequestContext.php
tests/phpunit/Authentication/LoginTest.php
tests/phpunit/Authentication/OAuth10Test.php
tests/phpunit/Authentication/OAuth20LoginTest.php
tests/phpunit/Authentication/OAuth20Test.php
tests/phpunit/Context/OAuth20ContextTest.php
tests/phpunit/Context/OAuth20LoginContextTest.php
tests/phpunit/Context/RequestContextTest.php

Jira: https://keboola.atlassian.net/browse/COM-596
Nemerguje sa do mastra ale do (vid koment tam): https://github.com/keboola/generic-extractor/pull/138
(980 riadkov su zmeny v `composer.lock`).
Tento PR obsahuje refactoring 3 auth tried: `OAuth10`, `OAuth20`, `OAuth20Login`.
**Po MERGE https://github.com/keboola/generic-extractor/pull/139 to REBASNEM.**

Update Guzzle - refactored auth: OAuth10, OAuth20, OAuthLogin

---

.travis.yml
composer.lock
doc/examples/081-login-auth-headers-query-override/users.request
doc/examples/081-login-auth-headers-query-override/users.requestHeaders
doc/examples/108-incremental-load-date/users.request
src/Authentication/Login.php
src/Authentication/OAuth20.php
src/Authentication/OAuth20Login.php
src/Cache/CacheAllStrategy.php
src/Context/RequestContext.php
src/GenericExtractor.php
src/Logger/LoggerMiddleware.php
src/MissingTableHelper.php
src/Utils.php
tests/phpunit/ExtractorTestCase.php
tests/phpunit/GenericExtractorJobTest.php
tests/phpunit/GenericExtractorTest.php
tests/phpunit/MissingTableHelperTest.php
tests/phpunit/MockExecutionTest.php
tests/phpunit/RecursiveJobTest.php
tests/phpunit/UtilsTest.php

Jira: https://keboola.atlassian.net/browse/COM-596
Nemerguje sa do mastra ale do (vid koment tam): https://github.com/keboola/generic-extractor/pull/138
Tento PR opravuje zostavajuce testy, ktore neprechadzali / boli vypnute.
**Po MERGE https://github.com/keboola/generic-extractor/pull/144 to REBASNEM.**

Update guzzle - other tests

---

docker-compose.yml
docker/jsontest/Dockerfile
docker/jsontest/JsonTests.pl
tests/phpunit/data/noCache/config.json
tests/phpunit/data/requestCache/config.json
tests/phpunit/data/requestCacheTTL/config.json

Jira: https://keboola.atlassian.net/browse/COM-596

Use local jsontest service

---

composer.json
composer.lock
src/Authentication/Login.php

Jira: https://keboola.atlassian.net/browse/COM-596

Update Juicer to 5.0.2: Fix host header in defaults

---

src/GenericExtractorJob.php
src/PlaceholdersUtils.php
tests/phpunit/GenericExtractorJobTest.php

Jira: https://keboola.atlassian.net/browse/COM-802
Changes:
- Befor bug fix -> there is needed some cleanup.

Move placeholders methods to PlaceholdersUtils

---

tests/phpunit/GenericExtractorJobTest.php
tests/phpunit/PlaceholdersUtilsTest.php

JIra: https://keboola.atlassian.net/browse/COM-802

Move tests

---

composer.json
composer.lock
doc/examples/143-aws-signature-request/_sample_out/mock-server.users
doc/examples/143-aws-signature-request/_sample_out/mock-server.users.manifest
doc/examples/143-aws-signature-request/config.json
doc/examples/143-aws-signature-request/users.request
doc/examples/143-aws-signature-request/users.requestHeaders
doc/examples/143-aws-signature-request/users.response
doc/run-samples.sh
src/AwsSignature/AwsSignatureMiddleware.php
src/Configuration/Extractor.php
src/Configuration/Extractor/ConfigFile.php
src/Configuration/Extractor/Node/AwsSignature.php
src/Executor.php
src/GenericExtractor.php

Jira - https://keboola.atlassian.net/browse/COM-1203

aws signature requests

---

composer.json
composer.lock

Related to: https://github.com/keboola/juicer/pull/41

Update keboola/juicer 5.0.3 => 5.0.4

---

src/Configuration/Api.php
src/GenericExtractor.php
tests/phpunit/Config/ApiTest.php

ZD: https://keboola.zendesk.com/agent/tickets/21643

Configuration: add "api.http.connectTimeout", "api.http.requestTimeout"

---

composer.lock

https://keboola.atlassian.net/browse/COM-1191

Upgrade keboola/codebuilder

---

src/PlaceholdersUtils.php
tests/phpunit/PlaceholdersUtilsTest.php

JIRA: https://keboola.atlassian.net/browse/CM-271

Cast getPlaceholderValue argument data type to string

---

README.md
src/Configuration/Extractor.php
tests/phpunit/Config/ConfigurationTest.php

JIRA: https://keboola.atlassian.net/browse/CM-475
Validuju to mimo config, protože je to tam tak všude jinde. A `InvalidConfigurationException` se tam potlačují 🤷‍♂️

Validate cert values

---

src/Executor.php

JIRA: https://keboola.atlassian.net/browse/CM-504

Fix trailing slash in path (causing No such file or directory)

---

src/Authentication/Login.php

JIRA: https://keboola.atlassian.net/browse/CM-549

Return null if expiration is empty

---

src/Authentication/Login.php
src/Authentication/OAuth20.php
src/GenericExtractor.php
src/Utils.php
tests/phpunit/FunctionalTest.php
tests/phpunit/data/invalidHeadersConfigOauth/config.json

JIRA: https://keboola.atlassian.net/browse/CM-272

Check for stdClass in header everywhere

---

src/Configuration/Api.php
tests/phpunit/Config/ApiTest.php

JIRA: https://keboola.atlassian.net/browse/CM-630

Check if page limit has valid data type a throw user exception if not

---

.github/workflows/push.yml
python-sync-actions/src/user_functions.py
python-sync-actions/tests/test_functions.py

Hotfix strtotime function
https://keboola.atlassian.net/browse/CFT-3029

Bug fix strtotime

---

.github/workflows/push.yml
README.md
doc/run-samples.sh
doc/run-single-example.sh
python-sync-actions/README.md
python-sync-actions/src/component.py
python-sync-actions/src/configuration.py
python-sync-actions/tests/data_tests/test_006_post_form/config.json
python-sync-actions/tests/test_component.py
python-sync-actions/tests/test_configuration.py

- FROM POST mode was not sending POST requests
- Body is not url-encoded when FORM
- Minor fixes
- tests
Tested in clients project also https://connection.north-europe.azure.keboola.com/admin/projects/21532/branch/305409/components/ex-generic-v2/83130722/menu/endpoint-0

CFT-3054 Fix/request body string

---

README.md
composer.lock

update balicka php-codebuilder pre podporu novej hash fcie

Update CFT-3235 - update new version of codebuilder package
